import mongoose from "mongoose";

// Schema for products
const productSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true, // Remove extra spaces from beginning/end
    },

    description: {
      type: String,
      required: true,
    },

    primary_category: {
      type: String, // Generated by AI
    },

    sustainability_filters: [
      String, // e.g. eco-friendly, recycled, biodegradable, etc.
    ],
  },
  {
    timestamps: true, // Automatically adds createdAt & updatedAt
  }
);

// Enable text search on name + description
productSchema.index({ name: "text", description: "text" });

const Product = mongoose.model("Product", productSchema);

export default Product;